[workspace]
resolver = "3"
members = [
  "runtime",
  "distribution",
  "dependencies/authentication",
  "dependencies/alarm",
  "dependencies/clock",
  "dependencies/data",
  "dependencies/events/sqlite",
  "dependencies/events/jetstream",
  "dependencies/execution-context",
  "dependencies/synchronization",
  "dependencies/telemetry",
  "dependencies/http",
  "dependencies/identifiers",
  "dependencies/timer",
  "fixtures/recorder",
]
