[package]
name = "kit-server-runtime"
version = "0.0.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
futures-util = "0.3.31"
indexmap = "2.12.1"
serde_json = { version = "1.0.145", features = ["preserve_order"] }
tokio = { version = "1.48.0", features = ["macros", "rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt"] }
