[package]
name = "kit-server-authentication"
version = "0.0.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
ed25519-dalek = "2.2.0"
kit-server-runtime = { path = "../../../../../compiler/rust/runtime" }
rusqlite = { version = "0.40.1", features = ["bundled"] }
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["v4"] }
