export type {
  Application,
  ApplicationContract,
  ApplicationFeatures,
  ApplicationMetadata,
  EnvironmentContract,
  EnvironmentDefinition,
  Feature,
  FeatureContract,
  FeatureDefinitions,
  FeatureUIAPIs,
  PlatformContract,
  PlacedFeature,
  PresentationName,
  Program,
  ProgramContract,
  ProgramOwner,
  ProgramNamesIn,
  ProgramProvides,
  ProgramRequires,
  ProgramStartContext,
  UIActions,
  UIActionContext,
  UIContributionAPI,
  UIState,
} from "@/core/application";
export { placePrograms } from "@/core/application";
export {
  bindCapabilitiesToScope,
  createProgramContributionInstance,
  createUIContributionInstance,
  ResourceScope,
  startProcess,
} from "@/core/process";
export type { Process, ProgramContributionInstance, UIContributionInstance } from "@/core/process";
export { collectExternalCapabilityNames, collectProgramManifest } from "@/core/capability";
export type {
  ProgramContributionAddress,
  ProgramContributionManifest,
  ProgramExternalCapabilities,
  ProgramManifest,
  ProgramName,
  ProgramProvidedCapabilities,
  ProgramRequiredCapabilities,
} from "@/core/capability";
export type {
  ComponentActionArgs,
  ComponentActionContext,
  ComponentActions,
  ComponentCapabilities,
  ComponentComposition,
  ComponentContract,
  ComponentContractOf,
  ComponentDefinition,
  ComponentDefinitions,
  ComponentElement,
  ComponentElementName,
  ComponentElements,
  ComponentFeatureAPI,
  ComponentMountContext,
  ComponentName,
  ComponentOwner,
  ComponentProps,
  ComponentRenderers,
  ComponentSlots,
  ComponentState,
  ComponentStateInput,
  ComponentUI,
  ComponentViewContext,
  RootComponentName,
} from "@/core/component";
export type {
  UIChild,
  UIContract,
  UIDefinition,
  UIElement,
  UIElementName,
  UIElementProps,
  UIElementTarget,
  UITarget,
} from "@/core/ui";
export type {
  ActionCompleted,
  ActionEvent,
  ActionEvents,
  ActionFailed,
  ActionStarted,
  Animation,
  AnimationSample,
  ConfiguredPresentation,
  Event,
  InvocationId,
  Presentation,
  PresentationAdapter,
  PresentationAdapterInstance,
  PresentationAdapterSession,
  PresentationComponentDeclaration,
  PresentationComponentInput,
  PresentationComponentTree,
  PresentationDefinition,
  PresentationData,
  PresentationElement,
  PresentationElementResolver,
  PresentationFrame,
  PresentationLanguage,
} from "@/core/presentation";
export { animate, createPresentationFrame, settled, velocity } from "@/core/presentation";
export { selectPlatformAdapters } from "@/contracts/platform";
export type {
  ComponentAdapter,
  ComponentAdapterSession,
  DevelopmentSession,
  PlatformAdapter,
  PlatformAdapterImplementation,
  PlatformAdapters,
  PlatformDevelopmentInput,
  PlatformInput,
  PlatformProductionInput,
  ProgramHostFactory,
  ProgramHostInput,
  ProductionArtifact,
  ProductionArtifacts,
  UIAdapter,
} from "@/contracts/platform";
export { bindEntityPrincipal, createEntity, EntityFailure } from "@/features/entity";
export type {
  Clock,
  DefinedEntityFeature,
  EntityApi,
  EntityActions,
  EntityAuthorization,
  EntityEvent,
  EntityFailureCode,
  EntityFeature,
  EntityImplementation,
  EntityModel,
  EntityModelDefinition,
  EntityPrincipal,
  EntityService,
  EntitySnapshot,
  EntityState,
  EntityMutation,
  EntitySynchronization,
  EntityValue,
  EventStore,
  Identifiers,
  StoredEvent,
} from "@/features/entity";
export { createIdentity } from "@/features/identity";
export type {
  AuthenticatedUser,
  AuthenticationBackend,
  IdentityClient,
  IdentityFeature,
  IdentityImplementation,
  IdentityModel,
  IdentityModelDefinition,
  IdentitySession,
  IdentityService,
} from "@/features/identity";
export { createEntityFixture, createMemoryEventStore } from "@/features/entity.testing";
