export type { WebUI } from "../platform";
export type {
  WebAffordance,
  WebColor,
  WebCondition,
  WebFill,
  WebFontFamily,
  WebGradientStop,
  WebGridTrack,
  WebLayout,
  WebLayoutModel,
  WebLength,
  WebLogicalBox,
  WebMeasure,
  WebMedia,
  WebPaint,
  WebPresentation,
  WebPresentationLanguage,
  WebQueryLength,
  WebShadow,
  WebStroke,
  WebStyle,
  WebStyleFragment,
  WebStyleRule,
  WebText,
  WebTransform,
} from "./language";
